import React from "react";
import { Transactions, columns } from "./columns";
import { DataTable } from "./data-table";

export default async function TransactionsPage() {
  const data: Transactions[] = [
    {
      avatar: "/images/Person-1.jpg",
      name: "Emma Richardson",
      category: "General",
      date: "2024-08-19T14:23:11Z",
      amount: 75.5,
      recurring: false,
    },
    {
      avatar: "/images/Logo-1.jpg",
      name: "Savory Bites Bistro",
      category: "Dining Out",
      date: "2024-08-19T20:23:11Z",
      amount: -55.5,
      recurring: false,
    },
    {
      avatar: "/images/Person-3.jpg",
      name: "Daniel Carter",
      category: "General",
      date: "2024-08-18T09:45:32Z",
      amount: -42.3,
      recurring: false,
    },
    {
      avatar: "/images/Person-4.jpg",
      name: "Sun Park",
      category: "General",
      date: "2024-08-17T16:12:05Z",
      amount: 120.0,
      recurring: false,
    },
    {
      avatar: "/images/Logo-2.jpg",
      name: "Urban Services Hub",
      category: "General",
      date: "2024-08-17T21:08:09Z",
      amount: -65.0,
      recurring: false,
    },
    {
      avatar: "/images/Person-6.jpg",
      name: "Liam Hughes",
      category: "Groceries",
      date: "2024-08-15T18:20:33Z",
      amount: 65.75,
      recurring: false,
    },
    {
      avatar: "/images/Person-7.jpg",
      name: "Lily Ramirez",
      category: "General",
      date: "2024-08-14T13:05:27Z",
      amount: 50.0,
      recurring: false,
    },
    {
      avatar: "/images/Person-8.jpg",
      name: "Ethan Clark",
      category: "Dining Out",
      date: "2024-08-13T20:15:59Z",
      amount: -32.5,
      recurring: false,
    },
    {
      avatar: "/images/Person-9.jpg",
      name: "James Thompson",
      category: "Entertainment",
      date: "2024-08-11T15:45:38Z",
      amount: -5.0,
      recurring: false,
    },
    {
      avatar: "/images/Logo-3.jpg",
      name: "Pixel Playground",
      category: "Entertainment",
      date: "2024-08-11T18:45:38Z",
      amount: -10.0,
      recurring: true,
    },
    {
      avatar: "/images/Person-11.jpg",
      name: "Ella Phillips",
      category: "Dining Out",
      date: "2024-08-10T19:22:51Z",
      amount: -45.0,
      recurring: false,
    },
    {
      avatar: "/images/Person-12.jpg",
      name: "Sofia Peterson",
      category: "Transportation",
      date: "2024-08-08T08:55:17Z",
      amount: -15.0,
      recurring: false,
    },
    {
      avatar: "/images/Person-13.jpg",
      name: "Mason Martinez",
      category: "Lifestyle",
      date: "2024-08-07T17:40:29Z",
      amount: -35.25,
      recurring: false,
    },
    {
      avatar: "/images/Logo-4.jpg",
      name: "Green Plate Eatery",
      category: "Groceries",
      date: "2024-08-06T08:25:44Z",
      amount: -78.5,
      recurring: false,
    },
    {
      avatar: "/images/Person-15.jpg",
      name: "Sebastian Cook",
      category: "Transportation",
      date: "2024-08-06T10:05:44Z",
      amount: -22.5,
      recurring: false,
    },
    {
      avatar: "/images/Person-1.jpg",
      name: "William Harris",
      category: "Personal Care",
      date: "2024-08-05T14:30:56Z",
      amount: -10.0,
      recurring: false,
    },
    {
      avatar: "/images/Logo-5.jpg",
      name: "Elevate Education",
      category: "Education",
      date: "2024-08-04T11:15:22Z",
      amount: -50.0,
      recurring: true,
    },
    {
      avatar: "/images/Logo-6.jpg",
      name: "Serenity Spa & Wellness",
      category: "Personal Care",
      date: "2024-08-03T14:00:37Z",
      amount: -30.0,
      recurring: true,
    },
    {
      avatar: "/images/Logo-7.jpg",
      name: "Spark Electric Solutions",
      category: "Bills",
      date: "2024-08-02T09:25:11Z",
      amount: -100.0,
      recurring: true,
    },
    {
      avatar: "/images/Person-5.jpg",
      name: "Rina Sato",
      category: "Bills",
      date: "2024-08-02T13:31:11Z",
      amount: -50.0,
      recurring: false,
    },
    {
      avatar: "/images/Logo-8.jpg",
      name: "Swift Ride Share",
      category: "Transportation",
      date: "2024-08-01T18:40:33Z",
      amount: -18.75,
      recurring: false,
    },
    {
      avatar: "/images/Logo-9.jpg",
      name: "Aqua Flow Utilities",
      category: "Bills",
      date: "2024-07-30T13:20:14Z",
      amount: -100.0,
      recurring: true,
    },
    {
      avatar: "/images/Logo-10.jpg",
      name: "EcoFuel Energy",
      category: "Bills",
      date: "2024-07-29T11:55:29Z",
      amount: -35.0,
      recurring: true,
    },
    {
      avatar: "/images/Person-9.jpg",
      name: "Yuna Kim",
      category: "Dining Out",
      date: "2024-07-29T13:51:29Z",
      amount: -28.5,
      recurring: false,
    },
    {
      avatar: "/images/Logo-11.jpg",
      name: "Flavor Fiesta",
      category: "Dining Out",
      date: "2024-07-27T20:15:06Z",
      amount: -42.75,
      recurring: false,
    },
    {
      avatar: "/images/Person-11.jpg",
      name: "Harper Edwards",
      category: "Shopping",
      date: "2024-07-26T09:43:23Z",
      amount: -89.99,
      recurring: false,
    },
    {
      avatar: "/images/Logo-12.jpg",
      name: "Buzz Marketing Group",
      category: "General",
      date: "2024-07-26T14:40:23Z",
      amount: 3358.0,
      recurring: false,
    },
    {
      avatar: "/images/Logo-13.jpg",
      name: "TechNova Innovations",
      category: "Shopping",
      date: "2024-07-25T16:25:37Z",
      amount: -29.99,
      recurring: false,
    },
    {
      avatar: "/images/Logo-14.jpg",
      name: "ByteWise",
      category: "Lifestyle",
      date: "2024-07-23T09:35:14Z",
      amount: -49.99,
      recurring: true,
    },
    {
      avatar: "/images/Logo-15.jpg",
      name: "Nimbus Data Storage",
      category: "Bills",
      date: "2024-07-21T10:05:42Z",
      amount: -9.99,
      recurring: true,
    },
    {
      avatar: "/images/Person-1.jpg",
      name: "Emma Richardson",
      category: "General",
      date: "2024-07-20T17:30:55Z",
      amount: -25.0,
      recurring: false,
    },
    {
      avatar: "/images/Person-2.jpg",
      name: "Daniel Carter",
      category: "General",
      date: "2024-07-19T12:45:09Z",
      amount: 50.0,
      recurring: false,
    },
    {
      avatar: "/images/Person-3.jpg",
      name: "Sun Park",
      category: "General",
      date: "2024-07-18T19:20:23Z",
      amount: -38.5,
      recurring: false,
    },
    {
      avatar: "/images/Person-4.jpg",
      name: "Harper Edwards",
      category: "Shopping",
      date: "2024-07-17T14:55:37Z",
      amount: -29.99,
      recurring: false,
    },
    {
      avatar: "/images/Person-5.jpg",
      name: "Liam Hughes",
      category: "Groceries",
      date: "2024-07-16T10:10:51Z",
      amount: -52.75,
      recurring: false,
    },
    {
      avatar: "/images/Person-6.jpg",
      name: "Lily Ramirez",
      category: "General",
      date: "2024-07-15T16:35:04Z",
      amount: 75.0,
      recurring: false,
    },
    {
      avatar: "/images/Person-7.jpg",
      name: "Ethan Clark",
      category: "Dining Out",
      date: "2024-07-14T20:50:18Z",
      amount: -41.25,
      recurring: false,
    },
    {
      avatar: "/images/Person-8.jpg",
      name: "Rina Sato",
      category: "Entertainment",
      date: "2024-07-13T09:15:32Z",
      amount: -10.0,
      recurring: false,
    },
    {
      avatar: "/images/Person-9.jpg",
      name: "James Thompson",
      category: "Bills",
      date: "2024-07-12T13:40:46Z",
      amount: -95.5,
      recurring: false,
    },
    {
      avatar: "/images/Person-10.jpg",
      name: "Ella Phillips",
      category: "Dining Out",
      date: "2024-07-11T18:05:59Z",
      amount: -33.75,
      recurring: false,
    },
    {
      avatar: "/images/Person-11.jpg",
      name: "Yuna Kim",
      category: "Dining Out",
      date: "2024-07-10T12:30:13Z",
      amount: -27.5,
      recurring: false,
    },
    {
      avatar: "/images/Person-12.jpg",
      name: "Sofia Peterson",
      category: "Transportation",
      date: "2024-07-09T08:55:27Z",
      amount: -12.5,
      recurring: false,
    },
    {
      avatar: "/images/Person-13.jpg",
      name: "Mason Martinez",
      category: "Lifestyle",
      date: "2024-07-08T15:20:41Z",
      amount: -65.0,
      recurring: false,
    },
    {
      avatar: "/images/Person-14.jpg",
      name: "Sebastian Cook",
      category: "Transportation",
      date: "2024-07-07T11:45:55Z",
      amount: -20.0,
      recurring: false,
    },
    {
      avatar: "/images/Person-15.jpg",
      name: "William Harris",
      category: "General",
      date: "2024-07-06T17:10:09Z",
      amount: 20.0,
      recurring: false,
    },
    {
      avatar: "/images/Logo-10.jpg",
      name: "Elevate Education",
      category: "Education",
      date: "2024-07-05T11:15:22Z",
      amount: -50.0,
      recurring: true,
    },
    {
      avatar: "/images/Logo-9.jpg",
      name: "Serenity Spa & Wellness",
      category: "Personal Care",
      date: "2024-07-03T14:00:37Z",
      amount: -30.0,
      recurring: true,
    },
    {
      avatar: "/images/Logo-10.jpg",
      name: "Spark Electric Solutions",
      category: "Bills",
      date: "2024-07-02T09:25:51Z",
      amount: -100.0,
      recurring: true,
    },
    {
      avatar: "/images/Logo-10.jpg",
      name: "Swift Ride Share",
      category: "Transportation",
      date: "2024-07-02T19:50:05Z",
      amount: -16.5,
      recurring: false,
    },
  ];

  return (
    <div className="container flex flex-col gap-8">
      <h1 className="text-preset-1 text-grey-900">Transactions</h1>
      <DataTable columns={columns} data={data} />
    </div>
  );
}
